import os
from dotenv import load_dotenv

load_dotenv()

GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")

IMAGE_MODEL = "gemini-2.5-flash-image"
IMAGE_MODEL_COLORIZER = "gemini-3-pro-image-preview"
TEXT_MODEL = "gemini-2.5-flash"


CONTOUR_FINDER_MIN_OBJECT_SIZE = 50
ELLIPSE_FITTER_MAX_ECCENTRICITY = 0.95

# Shape Fitting Defaults
SHAPE_FITTING_MIN_OBJECT_SIZE = 30
SHAPE_FITTING_N_COLORS = 10

SHAPE_FITTING_CIRCLE_REL_ERROR_THRESH = 0.20
SHAPE_FITTING_MIN_RADIUS = 0.5
SHAPE_FITTING_MAX_RADIUS = 400.0
SHAPE_FITTING_MIN_CONTOUR_POINTS = 25
SHAPE_FITTING_MIN_ARC_FRACTION = 0.5

SHAPE_FITTING_ELLIPSE_ERROR_THRESH = 0.05

SHAPE_FITTING_MERGE_DIST_THRESH = 15.0
SHAPE_FITTING_MERGE_SIZE_THRESH = 15.0